name: nkm_nose_pins_llp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  flutter_svg: ^2.0.7
  permission_handler: ^10.4.3
  share_plus: ^7.1.0
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  video_player: ^2.7.0
  path_provider: ^2.0.15
  open_file: ^3.3.2
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.4
  firebase_messaging: ^14.6.5
  firebase_dynamic_links: ^5.3.4
  store_redirect: ^2.0.1
  lottie: ^2.5.0
  webview_flutter: ^4.2.2
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/lottie/

  fonts:
    - family: proxima_nova_regular
      fonts:
        - asset: assets/fonts/proxima_nova_regular.otf
    - family: proxima_nova_bold
      fonts:
        - asset: assets/fonts/proxima_nova_bold.otf
    - family: proxima_nova_thin
      fonts:
        - asset: assets/fonts/proxima_nova_thin.otf