// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZOiCsxdfQxuGfBw-_yku4QOI1bPP2lCU',
    appId: '1:534290823844:android:ff5197989aa8d73fe0c431',
    messagingSenderId: '534290823844',
    projectId: 'nkm-nose-pins-llp-80f0b',
    storageBucket: 'nkm-nose-pins-llp-80f0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNdr0ZZGssYoLzyqBWrLjU0ALUodBH3A',
    appId: '1:534290823844:ios:27dfbff798e628b8e0c431',
    messagingSenderId: '534290823844',
    projectId: 'nkm-nose-pins-llp-80f0b',
    storageBucket: 'nkm-nose-pins-llp-80f0b.appspot.com',
    androidClientId: '534290823844-76uhk2hqn5jj38bpld8qhuhjqponvntf.apps.googleusercontent.com',
    iosClientId: '534290823844-aqa1il7l223uptv4nb4sn0ahljh4od73.apps.googleusercontent.com',
    iosBundleId: 'com.org.nkmNosePinsLlp',
  );
}
