
import 'package:nkm_nose_pins_llp/custom_libs/country_code_lib/country_code_model.dart';

class CountryCodeData {
  static final List<CountryCodeModel> countryCodeModelList = [
    CountryCodeModel(
        code: 'IN',
        dialCode: '+91',
        name: 'India',
        flagUri: 'assets/png/flags/in.png',
        currencyCode: "INR",
        currencySymbol: "₹"),
    CountryCodeModel(
        code: 'AU',
        dialCode: '+61',
        name: 'Australia',
        flagUri: 'assets/png/flags/au.png',
        currencyCode: "AUD",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'US',
        dialCode: '+1',
        name: 'United States',
        flagUri: 'assets/png/flags/us.png',
        currencyCode: "USD",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'GB',
        dialCode: '+44',
        name: 'United Kingdom',
        flagUri: 'assets/png/flags/gb.png',
        currencyCode: "GBP",
        currencySymbol: "£"),
    CountryCodeModel(
        code: 'ZA',
        dialCode: '+27',
        name: 'South Africa',
        flagUri: 'assets/png/flags/za.png',
        currencyCode: "ZAR",
        currencySymbol: "R"),
    CountryCodeModel(
        code: 'CH',
        dialCode: '+41',
        name: 'Switzerland',
        flagUri: 'assets/png/flags/ch.png',
        currencyCode: "CHF",
        currencySymbol: "CHF"),
    CountryCodeModel(
        code: 'NZ',
        dialCode: '+64',
        name: 'New Zealand',
        flagUri: 'assets/png/flags/nz.png',
        currencyCode: "NZD",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'MY',
        dialCode: '+60',
        name: 'Malaysia',
        flagUri: 'assets/png/flags/my.png',
        currencyCode: "MYR",
        currencySymbol: "RM"),
    CountryCodeModel(
        code: 'JP',
        dialCode: '+81',
        name: 'Japan',
        flagUri: 'assets/png/flags/jp.png',
        currencyCode: "JPY",
        currencySymbol: "¥"),
    CountryCodeModel(
        code: 'IT',
        dialCode: '+39',
        name: 'Italy',
        flagUri: 'assets/png/flags/it.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'DE',
        dialCode: '+49',
        name: 'Germany',
        flagUri: 'assets/png/flags/de.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'CN',
        dialCode: '+86',
        name: 'China',
        flagUri: 'assets/png/flags/cn.png',
        currencyCode: "CNY",
        currencySymbol: "¥"),
    CountryCodeModel(
        code: 'BR',
        dialCode: '+55',
        name: 'Brazil',
        flagUri: 'assets/png/flags/br.png',
        currencyCode: "BRL",
        currencySymbol: "R\$"),
    CountryCodeModel(
        code: 'CA',
        dialCode: '+1',
        name: 'Canada',
        flagUri: 'assets/png/flags/ca.png',
        currencyCode: "CAD",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'FR',
        dialCode: '+33',
        name: 'France',
        flagUri: 'assets/png/flags/fr.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'PK',
        dialCode: '+92',
        name: 'Pakistan',
        flagUri: 'assets/png/flags/pk.png',
        currencyCode: "PKR",
        currencySymbol: "₨"),
    CountryCodeModel(
        code: 'ES',
        dialCode: '+34',
        name: 'Spain',
        flagUri: 'assets/png/flags/es.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'UA',
        dialCode: '+380',
        name: 'Ukraine',
        flagUri: 'assets/png/flags/ua.png',
        currencyCode: "UAH",
        currencySymbol: "₴"),
    CountryCodeModel(
        code: 'AE',
        dialCode: '+971',
        name: 'United Arab Emirates',
        flagUri: 'assets/png/flags/ae.png',
        currencyCode: "AED",
        currencySymbol: "د.إ"),
    CountryCodeModel(
        code: 'SG',
        dialCode: '+65',
        name: 'Singapore',
        flagUri: 'assets/png/flags/sg.png',
        currencyCode: "SGD",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'BD',
        dialCode: '+880',
        name: 'Bangladesh',
        flagUri: 'assets/png/flags/bd.png',
        currencyCode: "BDT",
        currencySymbol: "Tk"),
    CountryCodeModel(
        code: 'AR',
        dialCode: '+54',
        name: 'Argentina',
        flagUri: 'assets/png/flags/ar.png',
        currencyCode: "ARS",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'EG',
        dialCode: '+20',
        name: 'Egypt',
        flagUri: 'assets/png/flags/eg.png',
        currencyCode: "EGP",
        currencySymbol: "E£"),
    CountryCodeModel(
        code: 'TR',
        dialCode: '+90',
        name: 'Turkey',
        flagUri: 'assets/png/flags/tr.png',
        currencyCode: "TRY",
        currencySymbol: "₺"),
    CountryCodeModel(
        code: 'TW',
        dialCode: '+886',
        name: 'Taiwan',
        flagUri: 'assets/png/flags/tw.png',
        currencyCode: "TWD",
        currencySymbol: "NT\$"),
    CountryCodeModel(
        code: 'MM',
        dialCode: '+95',
        name: 'Myanmar',
        flagUri: 'assets/png/flags/mm.png',
        currencyCode: "MMK",
        currencySymbol: "K"),
    CountryCodeModel(
        code: 'DK',
        dialCode: '+45',
        name: 'Denmark',
        flagUri: 'assets/png/flags/dk.png',
        currencyCode: "DKK",
        currencySymbol: "Kr."),
    CountryCodeModel(
        code: 'NP',
        dialCode: '+977',
        name: 'Nepal',
        flagUri: 'assets/png/flags/np.png',
        currencyCode: "NPR",
        currencySymbol: "रु"),
    CountryCodeModel(
        code: 'BE',
        dialCode: '+32',
        name: 'Belgium',
        flagUri: 'assets/png/flags/be.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'TH',
        dialCode: '+66',
        name: 'Thailand',
        flagUri: 'assets/png/flags/th.png',
        currencyCode: "THB",
        currencySymbol: "฿"),
    CountryCodeModel(
        code: 'AT',
        dialCode: '+43',
        name: 'Austria',
        flagUri: 'assets/png/flags/at.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'FI',
        dialCode: '+358',
        name: 'Finland',
        flagUri: 'assets/png/flags/fi.png',
        currencyCode: "FIM",
        currencySymbol: "Mk"),
    CountryCodeModel(
        code: 'AF',
        dialCode: '+93',
        name: 'Afghanistan',
        flagUri: 'assets/png/flags/af.png',
        currencyCode: "AFN",
        currencySymbol: "؋"),
    CountryCodeModel(
        code: 'CO',
        dialCode: '+57',
        name: 'Colombia',
        flagUri: 'assets/png/flags/co.png',
        currencyCode: "COP",
        currencySymbol: "\$"),
    CountryCodeModel(
        code: 'GR',
        dialCode: '+30',
        name: 'Greece',
        flagUri: 'assets/png/flags/gr.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'GL',
        dialCode: '+299',
        name: 'Greenland',
        flagUri: 'assets/png/flags/gl.png',
        currencyCode: "DKK",
        currencySymbol: "Kr."),
    CountryCodeModel(
        code: 'GE',
        dialCode: '+995',
        name: 'Georgia',
        flagUri: 'assets/png/flags/ge.png',
        currencyCode: "GEL",
        currencySymbol: "ლ"),
    CountryCodeModel(
        code: 'IL',
        dialCode: '+972',
        name: 'Israel',
        flagUri: 'assets/png/flags/il.png',
        currencyCode: "ILS",
        currencySymbol: "₪"),
    CountryCodeModel(
        code: 'ID',
        dialCode: '+62',
        name: 'Indonesia',
        flagUri: 'assets/png/flags/id.png',
        currencyCode: "IDR",
        currencySymbol: "Rp"),
    CountryCodeModel(
        code: 'IR',
        dialCode: '+98',
        name: 'Iran',
        flagUri: 'assets/png/flags/ir.png',
        currencyCode: "IRR",
        currencySymbol: "﷼"),
    CountryCodeModel(
        code: 'IQ',
        dialCode: '+964',
        name: 'Iraq',
        flagUri: 'assets/png/flags/iq.png',
        currencyCode: "IQD",
        currencySymbol: "ع.د"),
    CountryCodeModel(
        code: 'IE',
        dialCode: '+353',
        name: 'Ireland',
        flagUri: 'assets/png/flags/ie.png',
        currencyCode: "EUR",
        currencySymbol: "€"),
    CountryCodeModel(
        code: 'VN',
        dialCode: '+84',
        name: 'Vietnam',
        flagUri: 'assets/png/flags/vn.png',
        currencyCode: "VND",
        currencySymbol: "₫"),
    CountryCodeModel(
        code: 'LK',
        dialCode: '+94',
        name: 'Sri Lanka',
        flagUri: 'assets/png/flags/lk.png',
        currencyCode: "LKR",
        currencySymbol: "Rs"),
    CountryCodeModel(
        code: 'HK',
        dialCode: '+852',
        name: 'Hong Kong',
        flagUri: 'assets/png/flags/hk.png',
        currencyCode: "HKD",
        currencySymbol: "HK\$"),
    CountryCodeModel(
        code: 'HU',
        dialCode: '+36',
        name: 'Hungary',
        flagUri: 'assets/png/flags/hu.png',
        currencyCode: "HUF",
        currencySymbol: "Ft"),
    CountryCodeModel(
        code: 'PH',
        dialCode: '+63',
        name: 'Philippines',
        flagUri: 'assets/png/flags/ph.png',
        currencyCode: "PHP",
        currencySymbol: "₱"),
    CountryCodeModel(
        code: 'PL',
        dialCode: '+48',
        name: 'Poland',
        flagUri: 'assets/png/flags/pl.png',
        currencyCode: "PLN",
        currencySymbol: "zł"),
    CountryCodeModel(
        code: 'MX',
        dialCode: '+52',
        name: 'Mexico',
        flagUri: 'assets/png/flags/mx.png',
        currencyCode: "MXN",
        currencySymbol: "Mex\$"),
    CountryCodeModel(
        code: 'SE',
        dialCode: '+46',
        name: 'Sweden',
        flagUri: 'assets/png/flags/se.png',
        currencyCode: "SEK",
        currencySymbol: "kr"),
    CountryCodeModel(
        code: 'SA',
        dialCode: '+966',
        name: 'Saudi Arabia',
        flagUri: 'assets/png/flags/sa.png',
        currencyCode: "SAR",
        currencySymbol: "SR"),
    CountryCodeModel(
        code: 'MC',
        dialCode: '+377',
        name: 'Monaco',
        flagUri: 'assets/png/flags/mc.png',
        currencyCode: "EUR",
        currencySymbol: "SR"),
    CountryCodeModel(
        code: 'MN',
        dialCode: '+976',
        name: 'Mongolia',
        flagUri: 'assets/png/flags/mn.png',
        currencyCode: "MNT",
        currencySymbol: "₮"),
    CountryCodeModel(
        code: 'NG',
        dialCode: '+234',
        name: 'Nigeria',
        flagUri: 'assets/png/flags/ng.png',
        currencyCode: "NGN",
        currencySymbol: "₦"),
    CountryCodeModel(
        code: 'VE',
        dialCode: '+58',
        name: 'Venezuela',
        flagUri: 'assets/png/flags/ve.png',
        currencyCode: "VED",
        currencySymbol: "Bs"),
    CountryCodeModel(
        code: 'NO',
        dialCode: '+47',
        name: 'Norway',
        flagUri: 'assets/png/flags/no.png',
        currencyCode: "NOK",
        currencySymbol: "kr"),
    CountryCodeModel(
        code: 'KR',
        dialCode: '+82',
        name: 'South Korea',
        flagUri: 'assets/png/flags/kr.png',
        currencyCode: "KRW",
        currencySymbol: "₩"),
    CountryCodeModel(
        code: 'MA',
        dialCode: '+212',
        name: 'Morocco',
        flagUri: 'assets/png/flags/ma.png',
        currencyCode: "MAD",
        currencySymbol: "MAD"),
    CountryCodeModel(
        code: 'NA',
        dialCode: '+264',
        name: 'Namibia',
        flagUri: 'assets/png/flags/na.png',
        currencyCode: "MAD",
        currencySymbol: "N\$"),
    CountryCodeModel(
        code: 'QA',
        dialCode: '+974',
        name: 'Qatar',
        flagUri: 'assets/png/flags/qa.png',
        currencyCode: "QAR",
        currencySymbol: "QR"),

// //----------------------------------------------------------------------------------------------
//     CountryCodeModel(code:'RU',dialCode:'+7',name:'Russia',flagUri:'assets/png/flags/ru.png',currencyCode: ""),
//     CountryCodeModel(code:'AX',dialCode:'+358',name:'Åland Islands',flagUri:'assets/png/flags/ax.png'),
//     CountryCodeModel(code:'AL',dialCode:'+355',name:'Albania',flagUri:'assets/png/flags/al.png'),
//     CountryCodeModel(code:'DZ',dialCode:'+213',name:'Algeria',flagUri:'assets/png/flags/dz.png'),
//     CountryCodeModel(code:'AS',dialCode:'+1',name:'American Samoa',flagUri:'assets/png/flags/as.png'),
//     CountryCodeModel(code:'BQ',dialCode:'+599',name:'Caribbean Netherlands',flagUri:'assets/png/flags/bq.png'),
//     CountryCodeModel(code:'AD',dialCode:'+376',name:'Andorra',flagUri:'assets/png/flags/ad.png'),
//     CountryCodeModel(code:'AO',dialCode:'+244',name:'Angola',flagUri:'assets/png/flags/ao.png'),
//     CountryCodeModel(code:'NL',dialCode:'+31',name:'Netherlands',flagUri:'assets/png/flags/nl.png'),
//     CountryCodeModel(code:'AI',dialCode:'+1',name:'Anguilla',flagUri:'assets/png/flags/ai.png'),
//     CountryCodeModel(code:'AG',dialCode:'+1',name:'Antigua and Barbuda',flagUri:'assets/png/flags/ag.png'),
//     CountryCodeModel(code:'AM',dialCode:'+374',name:'Armenia',flagUri:'assets/png/flags/am.png'),
//     CountryCodeModel(code:'AW',dialCode:'+297',name:'Aruba',flagUri:'assets/png/flags/aw.png'),
//     CountryCodeModel(code:'AZ',dialCode:'+994',name:'Azerbaijan',flagUri:'assets/png/flags/az.png'),
//     CountryCodeModel(code:'BS',dialCode:'+1',name:'Bahamas',flagUri:'assets/png/flags/bs.png'),
//     CountryCodeModel(code:'BH',dialCode:'+973',name:'Bahrain',flagUri:'assets/png/flags/bh.png'),
//     CountryCodeModel(code:'BB',dialCode:'+1',name:'Barbados',flagUri:'assets/png/flags/bb.png'),
//     CountryCodeModel(code:'BY',dialCode:'+375',name:'Belarus',flagUri:'assets/png/flags/by.png'),
//     CountryCodeModel(code:'BZ',dialCode:'+501',name:'Belize',flagUri:'assets/png/flags/bz.png'),
//     CountryCodeModel(code:'BJ',dialCode:'+229',name:'Benin',flagUri:'assets/png/flags/bj.png'),
//     CountryCodeModel(code:'BM',dialCode:'+1',name:'Bermuda',flagUri:'assets/png/flags/bm.png'),
//     CountryCodeModel(code:'BT',dialCode:'+975',name:'Bhutan',flagUri:'assets/png/flags/bt.png'),
//     CountryCodeModel(code:'BO',dialCode:'+591',name:'Bolivia',flagUri:'assets/png/flags/bo.png'),
//     CountryCodeModel(code:'BA',dialCode:'+387',name:'Bosnia and Herzegovina',flagUri:'assets/png/flags/ba.png'),
//     CountryCodeModel(code:'BW',dialCode:'+267',name:'Botswana',flagUri:'assets/png/flags/bw.png'),
//     CountryCodeModel(code:'IO',dialCode:'+246',name:'British Indian Ocean Territory',flagUri:'assets/png/flags/io.png'),
//     CountryCodeModel(code:'VG',dialCode:'+1',name:'British Virgin Islands',flagUri:'assets/png/flags/vg.png'),
//     CountryCodeModel(code:'BN',dialCode:'+673',name:'Brunei',flagUri:'assets/png/flags/bn.png'),
//     CountryCodeModel(code:'BG',dialCode:'+359',name:'Bulgaria',flagUri:'assets/png/flags/bg.png'),
//     CountryCodeModel(code:'BF',dialCode:'+226',name:'Burkina Faso',flagUri:'assets/png/flags/bf.png'),
//     CountryCodeModel(code:'BI',dialCode:'+257',name:'Burundi',flagUri:'assets/png/flags/bi.png'),
//     CountryCodeModel(code:'KH',dialCode:'+855',name:'Cambodia',flagUri:'assets/png/flags/kh.png'),
//     CountryCodeModel(code:'CM',dialCode:'+237',name:'Cameroon',flagUri:'assets/png/flags/cm.png'),
//     CountryCodeModel(code:'CV',dialCode:'+238',name:'Cape Verde',flagUri:'assets/png/flags/cv.png'),
//     CountryCodeModel(code:'KY',dialCode:'+1',name:'Cayman Islands',flagUri:'assets/png/flags/ky.png'),
//     CountryCodeModel(code:'CF',dialCode:'+236',name:'Central African Republic',flagUri:'assets/png/flags/cf.png'),
//     CountryCodeModel(code:'TD',dialCode:'+235',name:'Chad',flagUri:'assets/png/flags/td.png'),
//     CountryCodeModel(code:'CL',dialCode:'+56',name:'Chile',flagUri:'assets/png/flags/cl.png'),
//     CountryCodeModel(code:'CX',dialCode:'+61',name:'Christmas Island',flagUri:'assets/png/flags/cx.png'),
//     CountryCodeModel(code:'CC',dialCode:'+61',name:'Cocos [Keeling] Islands',flagUri:'assets/png/flags/cc.png'),
//     CountryCodeModel(code:'KM',dialCode:'+269',name:'Comoros',flagUri:'assets/png/flags/km.png'),
//     CountryCodeModel(code:'CD',dialCode:'+243',name:'Democratic Republic Congo',flagUri:'assets/png/flags/cd.png'),
//     CountryCodeModel(code:'CG',dialCode:'+242',name:'Republic of Congo',flagUri:'assets/png/flags/cg.png'),
//     CountryCodeModel(code:'CK',dialCode:'+682',name:'Cook Islands',flagUri:'assets/png/flags/ck.png'),
//     CountryCodeModel(code:'CR',dialCode:'+506',name:'Costa Rica',flagUri:'assets/png/flags/cr.png'),
//     CountryCodeModel(code:'HR',dialCode:'+385',name:'Croatia',flagUri:'assets/png/flags/hr.png'),
//     CountryCodeModel(code:'CU',dialCode:'+53',name:'Cuba',flagUri:'assets/png/flags/cu.png'),
//     CountryCodeModel(code:'CW',dialCode:'+599',name:'Curaçao',flagUri:'assets/png/flags/cw.png'),
//     CountryCodeModel(code:'CY',dialCode:'+357',name:'Cyprus',flagUri:'assets/png/flags/cy.png'),
//     CountryCodeModel(code:'CZ',dialCode:'+420',name:'Czech Republic',flagUri:'assets/png/flags/cz.png'),
//     CountryCodeModel(code:'DJ',dialCode:'+253',name:'Djibouti',flagUri:'assets/png/flags/dj.png'),
//     CountryCodeModel(code:'DM',dialCode:'+1',name:'Dominica',flagUri:'assets/png/flags/dm.png'),
//     CountryCodeModel(code:'DO',dialCode:'+1',name:'Dominican Republic',flagUri:'assets/png/flags/do.png'),
//     CountryCodeModel(code:'TL',dialCode:'+670',name:'East Timor',flagUri:'assets/png/flags/tl.png'),
//     CountryCodeModel(code:'EC',dialCode:'+593',name:'Ecuador',flagUri:'assets/png/flags/ec.png'),
//     CountryCodeModel(code:'SV',dialCode:'+503',name:'El Salvador',flagUri:'assets/png/flags/sv.png'),
//     CountryCodeModel(code:'GQ',dialCode:'+240',name:'Equatorial Guinea',flagUri:'assets/png/flags/gq.png'),
//     CountryCodeModel(code:'ER',dialCode:'+291',name:'Eritrea',flagUri:'assets/png/flags/er.png'),
//     CountryCodeModel(code:'EE',dialCode:'+372',name:'Estonia',flagUri:'assets/png/flags/ee.png'),
//     CountryCodeModel(code:'SZ',dialCode:'+268',name:'Eswatini',flagUri:'assets/png/flags/sz.png'),
//     CountryCodeModel(code:'ET',dialCode:'+251',name:'Ethiopia',flagUri:'assets/png/flags/et.png'),
//     CountryCodeModel(code:'FK',dialCode:'+500',name:'Falkland Islands [Islas Malvinas]',flagUri:'assets/png/flags/fk.png'),
//     CountryCodeModel(code:'FO',dialCode:'+298',name:'Faroe Islands',flagUri:'assets/png/flags/fo.png'),
//     CountryCodeModel(code:'FJ',dialCode:'+679',name:'Fiji',flagUri:'assets/png/flags/fj.png'),
//     CountryCodeModel(code:'GF',dialCode:'+594',name:'French Guiana',flagUri:'assets/png/flags/gf.png'),
//     CountryCodeModel(code:'PF',dialCode:'+689',name:'French Polynesia',flagUri:'assets/png/flags/pf.png'),
//     CountryCodeModel(code:'GA',dialCode:'+241',name:'Gabon',flagUri:'assets/png/flags/ga.png'),
//     CountryCodeModel(code:'GM',dialCode:'+220',name:'Gambia',flagUri:'assets/png/flags/gm.png'),
//     CountryCodeModel(code:'GH',dialCode:'+233',name:'Ghana',flagUri:'assets/png/flags/gh.png'),
//     CountryCodeModel(code:'GI',dialCode:'+350',name:'Gibraltar',flagUri:'assets/png/flags/gi.png'),
//     CountryCodeModel(code:'GD',dialCode:'+1',name:'Grenada',flagUri:'assets/png/flags/gd.png'),
//     CountryCodeModel(code:'GP',dialCode:'+590',name:'Guadeloupe',flagUri:'assets/png/flags/gp.png'),
//     CountryCodeModel(code:'GU',dialCode:'+1',name:'Guam',flagUri:'assets/png/flags/gu.png'),
//     CountryCodeModel(code:'GT',dialCode:'+502',name:'Guatemala',flagUri:'assets/png/flags/gt.png'),
//     CountryCodeModel(code:'GG',dialCode:'+44',name:'Guernsey',flagUri:'assets/png/flags/gg.png'),
//     CountryCodeModel(code:'GN',dialCode:'+224',name:'Guinea Conakry',flagUri:'assets/png/flags/gn.png'),
//     CountryCodeModel(code:'GW',dialCode:'+245',name:'Guinea-Bissau',flagUri:'assets/png/flags/gw.png'),
//     CountryCodeModel(code:'GY',dialCode:'+592',name:'Guyana',flagUri:'assets/png/flags/gy.png'),
//     CountryCodeModel(code:'HT',dialCode:'+509',name:'Haiti',flagUri:'assets/png/flags/ht.png'),
//     CountryCodeModel(code:'HM',dialCode:'+672',name:'Heard Island and McDonald Islands',flagUri:'assets/png/flags/hm.png'),
//     CountryCodeModel(code:'HN',dialCode:'+504',name:'Honduras',flagUri:'assets/png/flags/hn.png'),
//     CountryCodeModel(code:'IS',dialCode:'+354',name:'Iceland',flagUri:'assets/png/flags/is.png'),
//     CountryCodeModel(code:'IM',dialCode:'+44',name:'Isle of Man',flagUri:'assets/png/flags/im.png'),
//     CountryCodeModel(code:'JM',dialCode:'+1',name:'Jamaica',flagUri:'assets/png/flags/jm.png'),
//     CountryCodeModel(code:'JE',dialCode:'+44',name:'Jersey',flagUri:'assets/png/flags/je.png'),
//     CountryCodeModel(code:'JO',dialCode:'+962',name:'Jordan',flagUri:'assets/png/flags/jo.png'),
//     CountryCodeModel(code:'KZ',dialCode:'+7',name:'Kazakhstan',flagUri:'assets/png/flags/kz.png'),
//     CountryCodeModel(code:'KE',dialCode:'+254',name:'Kenya',flagUri:'assets/png/flags/ke.png'),
//     CountryCodeModel(code:'KI',dialCode:'+686',name:'Kiribati',flagUri:'assets/png/flags/ki.png'),
//     CountryCodeModel(code:'XK',dialCode:'+386',name:'Kosovo',flagUri:'assets/png/flags/xk.png'),
//     CountryCodeModel(code:'KW',dialCode:'+965',name:'Kuwait',flagUri:'assets/png/flags/kw.png'),
//     CountryCodeModel(code:'KG',dialCode:'+996',name:'Kyrgyzstan',flagUri:'assets/png/flags/kg.png'),
//     CountryCodeModel(code:'LA',dialCode:'+856',name:'Laos',flagUri:'assets/png/flags/la.png'),
//     CountryCodeModel(code:'LV',dialCode:'+371',name:'Latvia',flagUri:'assets/png/flags/lv.png'),
//     CountryCodeModel(code:'LB',dialCode:'+961',name:'Lebanon',flagUri:'assets/png/flags/lb.png'),
//     CountryCodeModel(code:'LS',dialCode:'+266',name:'Lesotho',flagUri:'assets/png/flags/ls.png'),
//     CountryCodeModel(code:'LR',dialCode:'+231',name:'Liberia',flagUri:'assets/png/flags/lr.png'),
//     CountryCodeModel(code:'LY',dialCode:'+218',name:'Libya',flagUri:'assets/png/flags/ly.png'),
//     CountryCodeModel(code:'LI',dialCode:'+423',name:'Liechtenstein',flagUri:'assets/png/flags/li.png'),
//     CountryCodeModel(code:'LT',dialCode:'+370',name:'Lithuania',flagUri:'assets/png/flags/lt.png'),
//     CountryCodeModel(code:'LU',dialCode:'+352',name:'Luxembourg',flagUri:'assets/png/flags/lu.png'),
//     CountryCodeModel(code:'MO',dialCode:'+853',name:'Macau',flagUri:'assets/png/flags/mo.png'),
//     CountryCodeModel(code:'MK',dialCode:'+389',name:'Macedonia',flagUri:'assets/png/flags/mk.png'),
//     CountryCodeModel(code:'MG',dialCode:'+261',name:'Madagascar',flagUri:'assets/png/flags/mg.png'),
//     CountryCodeModel(code:'MW',dialCode:'+265',name:'Malawi',flagUri:'assets/png/flags/mw.png'),
//     CountryCodeModel(code:'MV',dialCode:'+960',name:'Maldives',flagUri:'assets/png/flags/mv.png'),
//     CountryCodeModel(code:'ML',dialCode:'+223',name:'Mali',flagUri:'assets/png/flags/ml.png'),
//     CountryCodeModel(code:'MT',dialCode:'+356',name:'Malta',flagUri:'assets/png/flags/mt.png'),
//     CountryCodeModel(code:'MH',dialCode:'+692',name:'Marshall Islands',flagUri:'assets/png/flags/mh.png'),
//     CountryCodeModel(code:'MQ',dialCode:'+596',name:'Martinique',flagUri:'assets/png/flags/mq.png'),
//     CountryCodeModel(code:'MR',dialCode:'+222',name:'Mauritania',flagUri:'assets/png/flags/mr.png'),
//     CountryCodeModel(code:'MU',dialCode:'+230',name:'Mauritius',flagUri:'assets/png/flags/mu.png'),
//     CountryCodeModel(code:'YT',dialCode:'+262',name:'Mayotte',flagUri:'assets/png/flags/yt.png'),
//     CountryCodeModel(code:'FM',dialCode:'+691',name:'Micronesia',flagUri:'assets/png/flags/fm.png'),
//     CountryCodeModel(code:'MD',dialCode:'+373',name:'Moldova',flagUri:'assets/png/flags/md.png'),
//     CountryCodeModel(code:'ME',dialCode:'+382',name:'Montenegro',flagUri:'assets/png/flags/me.png'),
//     CountryCodeModel(code:'MS',dialCode:'+1',name:'Montserrat',flagUri:'assets/png/flags/ms.png'),
//     CountryCodeModel(code:'MZ',dialCode:'+258',name:'Mozambique',flagUri:'assets/png/flags/mz.png'),
//     CountryCodeModel(code:'NR',dialCode:'+674',name:'Nauru',flagUri:'assets/png/flags/nr.png'),
//     CountryCodeModel(code:'NC',dialCode:'+687',name:'New Caledonia',flagUri:'assets/png/flags/nc.png'),
//     CountryCodeModel(code:'NI',dialCode:'+505',name:'Nicaragua',flagUri:'assets/png/flags/ni.png'),
//     CountryCodeModel(code:'NE',dialCode:'+227',name:'Niger',flagUri:'assets/png/flags/ne.png'),
//     CountryCodeModel(code:'NU',dialCode:'+683',name:'Niue',flagUri:'assets/png/flags/nu.png'),
//     CountryCodeModel(code:'NF',dialCode:'+672',name:'Norfolk Island',flagUri:'assets/png/flags/nf.png'),
//     CountryCodeModel(code:'KP',dialCode:'+850',name:'North Korea',flagUri:'assets/png/flags/kp.png'),
//     CountryCodeModel(code:'MP',dialCode:'+1',name:'Northern Mariana Islands',flagUri:'assets/png/flags/mp.png'),
//     CountryCodeModel(code:'OM',dialCode:'+968',name:'Oman',flagUri:'assets/png/flags/om.png'),
//     CountryCodeModel(code:'PW',dialCode:'+680',name:'Palau',flagUri:'assets/png/flags/pw.png'),
//     CountryCodeModel(code:'PS',dialCode:'+970',name:'Palestinian Territories',flagUri:'assets/png/flags/ps.png'),
//     CountryCodeModel(code:'PG',dialCode:'+675',name:'Papua New Guinea',flagUri:'assets/png/flags/pg.png'),
//     CountryCodeModel(code:'PY',dialCode:'+595',name:'Paraguay',flagUri:'assets/png/flags/py.png'),
//     CountryCodeModel(code:'PE',dialCode:'+51',name:'Peru',flagUri:'assets/png/flags/pe.png'),
//     CountryCodeModel(code:'PT',dialCode:'+351',name:'Portugal',flagUri:'assets/png/flags/pt.png'),
//     CountryCodeModel(code:'PR',dialCode:'+1',name:'Puerto Rico',flagUri:'assets/png/flags/pr.png'),
//     CountryCodeModel(code:'RE',dialCode:'+262',name:'Réunion',flagUri:'assets/png/flags/re.png'),
//     CountryCodeModel(code:'RO',dialCode:'+40',name:'Romania',flagUri:'assets/png/flags/ro.png'),
//     CountryCodeModel(code:'RW',dialCode:'+250',name:'Rwanda',flagUri:'assets/png/flags/rw.png'),
//     CountryCodeModel(code:'BL',dialCode:'+590',name:'Saint Barthélemy',flagUri:'assets/png/flags/bl.png'),
//     CountryCodeModel(code:'SH',dialCode:'+290',name:'Saint Helena',flagUri:'assets/png/flags/sh.png'),
//     CountryCodeModel(code:'KN',dialCode:'+1',name:'St. Kitts',flagUri:'assets/png/flags/kn.png'),
//     CountryCodeModel(code:'LC',dialCode:'+1',name:'St. Lucia',flagUri:'assets/png/flags/lc.png'),
//     CountryCodeModel(code:'MF',dialCode:'+590',name:'Saint Martin',flagUri:'assets/png/flags/mf.png'),
//     CountryCodeModel(code:'PM',dialCode:'+508',name:'Saint Pierre and Miquelon',flagUri:'assets/png/flags/pm.png'),
//     CountryCodeModel(code:'VC',dialCode:'+1',name:'St. Vincent',flagUri:'assets/png/flags/vc.png'),
//     CountryCodeModel(code:'WS',dialCode:'+685',name:'Samoa',flagUri:'assets/png/flags/ws.png'),
//     CountryCodeModel(code:'SM',dialCode:'+378',name:'San Marino',flagUri:'assets/png/flags/sm.png'),
//     CountryCodeModel(code:'ST',dialCode:'+239',name:'São Tomé and Príncipe',flagUri:'assets/png/flags/st.png'),
//     CountryCodeModel(code:'SN',dialCode:'+221',name:'Senegal',flagUri:'assets/png/flags/sn.png'),
//     CountryCodeModel(code:'RS',dialCode:'+381',name:'Serbia',flagUri:'assets/png/flags/rs.png'),
//     CountryCodeModel(code:'SC',dialCode:'+248',name:'Seychelles',flagUri:'assets/png/flags/sc.png'),
//     CountryCodeModel(code:'SL',dialCode:'+232',name:'Sierra Leone',flagUri:'assets/png/flags/sl.png'),
//     CountryCodeModel(code:'SX',dialCode:'+1',name:'Sint Maarten',flagUri:'assets/png/flags/sx.png'),
//     CountryCodeModel(code:'SK',dialCode:'+421',name:'Slovakia',flagUri:'assets/png/flags/sk.png'),
//     CountryCodeModel(code:'SI',dialCode:'+386',name:'Slovenia',flagUri:'assets/png/flags/si.png'),
//     CountryCodeModel(code:'SB',dialCode:'+677',name:'Solomon Islands',flagUri:'assets/png/flags/sb.png'),
//     CountryCodeModel(code:'SO',dialCode:'+252',name:'Somalia',flagUri:'assets/png/flags/so.png'),
//     CountryCodeModel(code:'GS',dialCode:'+500',name:'South Georgia and the South Sandwich Islands',flagUri:'assets/png/flags/gs.png'),
//     CountryCodeModel(code:'SS',dialCode:'+211',name:'South Sudan',flagUri:'assets/png/flags/ss.png'),
//     CountryCodeModel(code:'SD',dialCode:'+249',name:'Sudan',flagUri:'assets/png/flags/sd.png'),
//     CountryCodeModel(code:'SR',dialCode:'+597',name:'Suriname',flagUri:'assets/png/flags/sr.png'),
//     CountryCodeModel(code:'SJ',dialCode:'+47',name:'Svalbard and Jan Mayen',flagUri:'assets/png/flags/sj.png'),
//     CountryCodeModel(code:'SY',dialCode:'+963',name:'Syria',flagUri:'assets/png/flags/sy.png'),
//     CountryCodeModel(code:'TJ',dialCode:'+992',name:'Tajikistan',flagUri:'assets/png/flags/tj.png'),
//     CountryCodeModel(code:'TZ',dialCode:'+255',name:'Tanzania',flagUri:'assets/png/flags/tz.png'),
//     CountryCodeModel(code:'TG',dialCode:'+228',name:'Togo',flagUri:'assets/png/flags/tg.png'),
//     CountryCodeModel(code:'TK',dialCode:'+690',name:'Tokelau',flagUri:'assets/png/flags/tk.png'),
//     CountryCodeModel(code:'TO',dialCode:'+676',name:'Tonga',flagUri:'assets/png/flags/to.png'),
//     CountryCodeModel(code:'TT',dialCode:'+1',name:'Trinidad/Tobago',flagUri:'assets/png/flags/tt.png'),
//     CountryCodeModel(code:'TN',dialCode:'+216',name:'Tunisia',flagUri:'assets/png/flags/tn.png'),
//     CountryCodeModel(code:'TM',dialCode:'+993',name:'Turkmenistan',flagUri:'assets/png/flags/tm.png'),
//     CountryCodeModel(code:'TC',dialCode:'+1',name:'Turks and Caicos Islands',flagUri:'assets/png/flags/tc.png'),
//     CountryCodeModel(code:'TV',dialCode:'+688',name:'Tuvalu',flagUri:'assets/png/flags/tv.png'),
//     CountryCodeModel(code:'VI',dialCode:'+1',name:'U.S. Virgin Islands',flagUri:'assets/png/flags/vi.png'),
//     CountryCodeModel(code:'UG',dialCode:'+256',name:'Uganda',flagUri:'assets/png/flags/ug.png'),
//     CountryCodeModel(code:'UY',dialCode:'+598',name:'Uruguay',flagUri:'assets/png/flags/uy.png'),
//     CountryCodeModel(code:'UZ',dialCode:'+998',name:'Uzbekistan',flagUri:'assets/png/flags/uz.png'),
//     CountryCodeModel(code:'VU',dialCode:'+678',name:'Vanuatu',flagUri:'assets/png/flags/vu.png'),
//     CountryCodeModel(code:'VA',dialCode:'+379',name:'Vatican City',flagUri:'assets/png/flags/va.png'),
//     CountryCodeModel(code:'WF',dialCode:'+681',name:'Wallis and Futuna',flagUri:'assets/png/flags/wf.png'),
//     CountryCodeModel(code:'EH',dialCode:'+212',name:'Western Sahara',flagUri:'assets/png/flags/eh.png'),
//     CountryCodeModel(code:'YE',dialCode:'+967',name:'Yemen',flagUri:'assets/png/flags/ye.png'),
//     CountryCodeModel(code:'ZM',dialCode:'+260',name:'Zambia',flagUri:'assets/png/flags/zm.png'),
  ];
}

// India,91,INR,₹
// Australia,61,AUD,$
// United States,1,USD,$
// United Kingdom,44,GBP,£
// South Africa,27,ZAR,R
// Switzerland,41,CHF,CHF
// New Zealand,64,NZD,$
// Malaysia,60,MYR,RM
// Japan,81,JPY,¥
// Italy,39,EUR,€
// Germany,49,EUR,€
// China,86,CNY,¥
// Brazil,55,BRL,R$
// Canada,1,CAD,$
// France,33,EUR,€
// Pakistan,92,PKR,₨
// Spain,34,EUR,€
// Ukraine,380,UAH,₴
// United Arab Emirates,971,AED,د.إ
// Singapore,65,SGD,$
// Bangladesh,880,BDT,Tk
// Argentina,54,ARS,$
// ---------------------
// Egypt,20,EGP,E£
// Turkey,90,TRY,₺
// Taiwan,886,TWD,NT$
// Myanmar,95,MMK,K
// Denmark,45,DKK,Kr.
// Nepal,977,NPR,रु
// Belgium,32,EUR,€
// Thailand,66,THB,฿
// Austria,43,EUR,€
// Finland,358,FIM,Mk
// Afghanistan,93,AFN,؋
// Colombia,57,COP,$
// Greece,30,EUR,€
// Greenland,299,DKK,Kr.
// Georgia,995,GEL,ლ
// Israel,972,ILS,₪
// Indonesia,62,IDR,Rp
// Iran,98,IRR,﷼
// Iraq,964,IQD,ع.د
// Ireland,353,EUR,€
// Vietnam,84,VND,₫
// Sri Lanka,94,LKR,Rs
// Hong Kong,852,HKD,HK$
// Hungary,36,HUF,Ft
// Philippines,63,PHP,₱
// Poland,48,PLN,zł
// Mexico,52,MXN,Mex$
// Sweden,46,SEK,kr
// Saudi Arabia,966,SAR,SR
// Monaco,377,EUR,SR
// Mongolia,976,MNT,₮
// Nigeria,234,NGN,₦
// Venezuela,58,VED,Bs
// Norway,47,NOK,kr
// South Korea,82,KRW,₩
// Morocco,212,MAD,MAD
// Namibia,264,MAD,N$
// Qatar,974,QAR,QR
